### ISSUE TITLE
NullReferenceExceptions on background thread?

### ISSUE THREAD

**Issue by mcintyre321** [mattcbaker/dotnetcore-slackbot#6]
Hi, I'm running your bot in LinqPad, but am getting an NRE when it hears a message. I think the error is on a background thread, which LinqPad is catching automatically, but it might cause issies on other hosts.

![image](https://cloud.githubusercontent.com/assets/275706/24039670/ef9b63ca-0afd-11e7-96b1-f2ce0ce8a763.png)

The bot still seems to work, but it's maybe only because LinqPad catches the error safely

PS your bot is awesome I've got lots of people at work using it on a hackday :)

**Comment by mattcbaker** [comment]
@mcintyre321 I'm glad that the bot is being useful! I have a guess on what this error might be, but not positive. Would you be willing to share the code you have in LINQPad?

**Comment by mcintyre321** [comment]
I think it was the code which parses the message text. Some messages (maybe likes etc.? have null text values)

**Comment by mattcbaker** [comment]
@mcintyre321 thank you for finding this one. I *think* I got it fixed. I was able to replicate the issue by sending a message and then editing it. Checked in the fix with commit b0408b25a5fbeeaac81b324649427b9224f8956d

Would you be willing to verify that it works on your end as well?

**Comment by mcintyre321** [comment]
Getting another error with the latest version from Nuget
![image](https://cloud.githubusercontent.com/assets/275706/24241245/0cac4bd4-0fac-11e7-93ac-a595d76656c5.png)

**Comment by mattcbaker** [comment]
Well, crap! I'll get a fix on, thank you for finding this.

**Comment by mattcbaker** [comment]
@mcintyre321 I don't have the developer edition of Linqpad, so I can't test your exact scenario. However, I think I've replicated your issue and implemented a stopgap with this commit: a6f1a4bba363d71cf24884e530cf170e61efd637

You were right, the problem seems related to non-message slack communication. I'm working on a broader fix now.

**Comment by mattcbaker** [comment]
@mcintyre321 I don't have the premium edition of LinqPad, so this was a bit difficult to reproduce. I did get it to occur on my end, though. Version `1.2.3` of Slackbot has the fixes that worked for me.

The fix is a bit of a stopgap, I'm working on a broader solution now. I'd love to hear whether or not it works on your end.
